select * from customer limit 5
--Q1. What is the total revenue generated by male vs.female Customers?

select gender, sum(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase
--amount?

select customer_id,purchase_amount
from customer
where discount_applied = 'Yes' AND purchase_amount >=(select avg(purchase_amount)
from customer)
--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating)::numeric, 2) AS average_review
from customer
group by item_purchased 
order by avg(review_rating)desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
 select shipping_type, Round (avg(purchase_amount),2) as average
 from customer
 group by shipping_type
 having shipping_type in ('Express', 'Standard')

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and 
--non-subscribers.
select subscription_status ,Count(customer_id), round(sum(purchase_amount)) as total_revenue ,Round( avg (purchase_amount),2 ) as average_spend
from customer
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased , 
round(100* sum(case when discount_applied = 'Yes' then 1 else 0 end )/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5 

--Q7. Segment Customers into New, Returning, and Loyal based on their total Of previous purchases, and Show the Count Of each segment.
with customer_types as (
select customer_id,previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases Between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)
select customer_segment,count(*)as "No of Customers"
from customer_types
group by customer_segment

--Q8. What are the top 3 most purchased products within each category
 
with item_counts as (
select category,item_purchased,
count(customer_id)as total_orders,
row_number()over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)
select item_rank , category,item_purchased,total_orders
from item_counts
where item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to
--subscribe
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--10. What is the revenue contribution of each age group?

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc








